### ISSUE TITLE
El formulario de contacto se corta en algunos dispositivos

### ISSUE THREAD

**Issue by Cyntekes** [Cyntekweb/Web-bugs#4]
En la web de contacto, el formulario de contacto se corta no pudiendo ver así el botón de enviar

**Comment by Hugmanrique121** [comment]
Arreglado en todos los dispositivos, la causa era que todas las <section> tenían un padding-bottom y top de 100px cuando en algunas <section> no debería de tener padding, ya de paso hemos arreglado la apariencia de los botones default que estaban cogiendo los estilos del de Enviar el formulario.
